# Remove all packages in the User Library (!) ----------------------------------
if (FALSE)
{
  lib <- "~/R/x86_64-pc-linux-gnu-library/3.6"
  remove.packages(dir(lib), lib = lib)
}

# Write a script to install package with its dependencies ----------------------
if (FALSE)
{
  setwd("~/github-repos/flusshygiene/packages/opencpu-base")
  source("R/functions.R")
  write_install_script(pkg = "testthat", "./R/install_testthat.R")
}

# write_install_script ---------------------------------------------------------
write_install_script <- function(pkg, con = stdout())
{
  db <- installed.packages()
  
  staged <- get_ordered_dependencies(pkg, db = db)
  
  strings <- lapply(c(staged, list(pkg)), function(x) {
    p <- db[x, "Version", drop = FALSE]
    sort(sprintf("%s:%s", rownames(p), p))
  })
  
  install <- function(x) {
    p <- strsplit(x, ":")[[1L]]
    remotes::install_version(
      p[1L], p[2L], dependencies = FALSE, upgrade = "never"
    )
  }
  
  writeLines(con = con, c(
    sprintf("# Generated by write_install_script() on %s", Sys.Date()),
    "install.packages(\"remotes\")",
    paste("install <-", paste(collapse = "\n", deparse(install))),
    sprintf("install(\"%s\")", unlist(strings))
  ))
}

# get_ordered_dependencies -----------------------------------------------------
get_ordered_dependencies <- function(x, db = NULL)
{
  staged <- list()
  
  all_pkgs <- tools::package_dependencies(x, db = db, recursive = TRUE)[[1L]]
  
  pkgs <- all_pkgs
  
  while(length(pkgs)) {

    cat(sprintf(
      "Still %d packages to stage\n", length(all_pkgs) - length(unlist(staged))
    ))
    
    deps <- lapply(
      tools::package_dependencies(pkgs, db = db, recursive = FALSE), 
      FUN = setdiff, 
      y = unique(unlist(staged))
    )
    
    new_pkgs <- names(which(lengths(deps) == 0L))

    staged[[length(staged) + 1L]] <- new_pkgs
    
    pkgs <- setdiff(pkgs, new_pkgs)
    
  } # wend

  stopifnot(identical(sort(unlist(staged)), sort(all_pkgs)))

  system_pkgs <- c(
    "stats", "graphics", "grDevices", "utils", "methods", "datasets", "base"
  )  
  
  staged <- lapply(staged, setdiff, system_pkgs)
  
  staged[lengths(staged) > 0L]
}
