// if (process.env.REACT_APP_MAPBOX_API_TOKEN === undefined) {
//   throw new Error('No env variable avaialabe');
//   // process.exit(1);
// }

const pkg = require('../package.json');
const fs = require('fs');
const path = require('path');
const version = pkg.version;

const outstring = `// this is autogenerated content on npm start. Don't edit by hand!\nexport const APP_VERSION = '${version}';\n`;

fs.writeFileSync(path.resolve(__dirname, '../src/version.ts'), outstring);
