name: Docker Image Build Test CI

on:
  push:
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: Docker login and build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
        run: |
          echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev" .
        # uses: actions/docker/login@master
      # - name: Docker build image
        # run: docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev" .
        # uses: actions/docker/cli-multi@master
        # with:
          # args: '"build --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ."'
