name: Docker Image CI

on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: Docker login and build and push
        # uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
        run: |
          echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev" .
          docker push "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"

      # - name: Docker Build and push the image
      #   uses: actions/docker/cli-multi@master
      #   with:
      #     args: '"build --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ." "push ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"'
