name: Build Docker Image CI

on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1

      - name: test and build source
        uses: actions/setup-node@master
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_REQ_URL: ${{ secrets.AUTH0_REQ_URL }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
        with:
          node-version: 10.x
      - run: npm ci --quiet
      - run: npm run build

      - name: Docker login, build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
        run: |
          echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev" .
          docker push "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"
        # uses: actions/docker/login@master

      # - name: Build and push the image
      # uses: actions/docker/cli-multi@master
      # with:
      # args: '"build --label version=${GITHUB_REF##*/} --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ." "push ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"'
