version: "3"

services:
  flusshygiene-opencpu-fhpredict-api:
    image: technologiestiftung/flusshygiene-opencpu-fhpredict-api:test-dev
    container_name: flusshygiene-opencpu-fhpredict-api
    env_file: ./.env
