module.exports = {
  AWS_BUCKET: 'FOO',
  ENV_SUFFIX: 'DEV',
  REDIS_HOST: '127.0.0.1',
  REDIS_PORT: 6379,
  SESSION_SECRET: 'foo',
  EXPRESS_RATE_LIMIT_MAX_REQUEST_PER_IP: 100,
  EXPRESS_RATE_LIMIT_MINUTE: 5,
};
