version: '3'
services:
  postgres:
    container_name: 'postgres-db'
    image: 'mdillon/postgis:10'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:5.0.10'
    ports:
      - '6379:6379'
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   env_file: .env
  #   ports:
  #     - 5004:5004
  #   depends_on:
  #     - redis
  #     - postgres
