language: node_js
node_js:
  - '10'
env:
  global:
    - CI=true
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm t -- --coverage --watchAll=false --color
  - npm run build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
