# docker-compose.yml
version: '3'
services:
  spa:
    # env_file: './.env'

    environment:
      - PORT=3000

    build:
      context: . # where to look for files
      dockerfile: Dockerfile
      #
      # https://github.com/docker/compose/issues/1837#issuecomment-316896858
      # https://github.com/docker/compose/issues/1837#issuecomment-316896858
      # When building a Docker image from the commandline, you can set those values using –build-arg:
      # docker build --build-arg some_variable_name=a_value
      args:
        - REACT_APP_MAPBOX_API_TOKEN=${REACT_APP_MAPBOX_API_TOKEN}
        - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENTID=${REACT_APP_AUTH0_CLIENTID}
        - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
        - REACT_APP_API_HOST=${REACT_APP_API_HOST}

    ports:
      - '3000:3000'
    # env_file: ./.env
