name: Docker Image CI

on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: Docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # AUTH0_REQ_URL: ${{ secrets.AUTH0_REQ_URL }}
          # AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          # AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          # AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          # API_URL: ${{ secrets.API_URL }}
          # ENDPOINT_PROD: ${{ secrets.ENDPOINT_PROD }}
          # TOKEN_PROD: ${{ secrets.TOKEN_PROD }}
          CI: true

      - name: Docker Build and push the image
        uses: actions/docker/cli-multi@master
        with:
          args: '"build --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ." "push ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"'
