name: Docker Image CI

on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: test and build source
        uses: actions/setup-node@master
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_REQ_URL: ${{ secrets.AUTH0_REQ_URL }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
        with:
          node-version: 10.x
      - run: npm ci

      - run: npm run build
      - name: Docker login build and push
        uses: actions/docker/cli-multi@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
      # - name: Build the Docker image
      # trim refs/tags/ from refs/tags/v0.1.2 with shell string operators
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: docker build . --file Dockerfile --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev
      #   - name: Push the Docker image
      - run: docker push ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev
