name: Docker Image Build Test CI

on:
  push:
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: Docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
      - name: Docker build image
        uses: actions/docker/cli-multi@master
        with:
          args: '"build --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ."'
