name: Docker Image CI

on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v1
      - name: Docker login, build and push
        # uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI: true
        run:  |
          echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build --label version=${GITHUB_REF##*/} --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev" .
          docker push "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"

      # - name: Build and push the image
        # uses: actions/docker/cli-multi@master
        # with:
          # args: '"build --label version=${GITHUB_REF##*/} --tag ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev ." "push ${GITHUB_REPOSITORY}:${GITHUB_REF##*/}-dev"'
