name: CRONBOT test and build
env:
  SUFFIX: cronbot
  STAGE: dev

on:
  push:
    paths:
      - 'packages/cronbot/src/**'
      - '.github/workflows/cronbot-tests.yml'
      - 'packages/cronbot/Dockerfile'
      - 'packages/cronbot/.dockerignore'
      - 'packages/cronbot/package*.json'
  pull_request:
    paths:
      - 'packages/cronbot/src/**'
      - '.github/workflows/cronbot-tests.yml'
      - 'packages/cronbot/Dockerfile'
      - 'packages/cronbot/.dockerignore'
      - 'packages/cronbot/package*.json'
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      # - name: Skip based on commit message
      #   uses: veggiemonk/skip-commit@1.0.0
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: create db.json
        run: touch packages/${SUFFIX}/db.json
      - name: npm install and test
        run: |
          cd packages/${SUFFIX}
          npm ci
          npm test --ci --coverage
          npm run build
        env:
          CI: "true"
  image:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/${SUFFIX}
          docker build --label version=${GITHUB_REF##*/} --tag ${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-${STAGE} .
        env:
          CI: "true"