name: Cronjob

env:
  AUTH0_TOKEN_ISSUER: ${{ secrets.AUTH0_TOKEN_ISSUER }}
  AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  API_HOST: ${{ secrets.API_HOST }}
  API_VERSION: ${{ secrets.API_VERSION }}
  FLSSHYGN_PREDICT_URL: ${{ secrets.FLSSHYGN_PREDICT_URL }}
  FLSSHYGN_CALIBRATE_URL: ${{ secrets.FLSSHYGN_CALIBRATE_URL }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PW: ${{ secrets.SMTP_PW }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_FROM: ${{ secrets.SMTP_FROM }}
  SMTP_ADMIN_TO: ${{ secrets.SMTP_ADMIN_TO }}

on:
  workflow_dispatch:
  schedule:
    # every day at 4
    # https://crontab.guru/#0_4_*_*_*
    - cron: '0 4 * * *'

jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: harvesting data for all bathingspots
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Exec Cronbot
        uses: technologiestiftung/flusshygiene-cronbot-action@v0.1.0
      # - name: Use Node.js from nvm
      # shell: bash -l {0}
      # run: nvm install
      # - name: install deps
      # run: npm ci
      # - name: exec
      # run: node index.js
