name: FHPREDICT API test and build
env:
  SUFFIX: "opencpu-fhpredict-api"
  COMMIT_FILTER: "[skip-ci]"

on:
  push:
    paths:
      - '.github/workflows/fhpredictapi-tests.yml'
      - 'packages/opencpu-fhpredict-api/Dockerfile'
      - 'packages/opencpu-fhpredict-api/.dockerignore'
      - 'packages/opencpu-fhpredict-api/package*.json'
      - 'packages/opencpu-fhpredict-api/opencpu-config/*'
      - 'packages/opencpu-fhpredict-api/files/*'
  pull_request:
    paths:
      - '.github/workflows/fhpredictapi-tests.yml'
      - 'packages/opencpu-fhpredict-api/Dockerfile'
      - 'packages/opencpu-fhpredict-api/.dockerignore'
      - 'packages/opencpu-fhpredict-api/package*.json'
      - 'packages/opencpu-fhpredict-api/opencpu-config/*'
      - 'packages/opencpu-fhpredict-api/files/*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # - name: Skip based on commit message
      #   uses: veggiemonk/skip-commit@1.0.0
      - name: Get te source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/opencpu-fhpredict-api/
          docker build --label version=${GITHUB_REF##*/} --tag "${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-dev" .
