name: MIDDLELAYER test and build
env:
  SUFFIX: opencpu-middlelayer
  STAGE: dev
  COMMIT_FILTER: '[skip-ci]'

on:
  push:
    paths:
      - '.github/workflows/middlelayer-tests.yml'
      - 'packages/opencpu-middlelayer/src/**'
      - 'packages/opencpu-middlelayer/__tests__/**'
      - 'packages/opencpu-middlelayer/package*.json'
      - 'packages/opencpu-middlelayer/Dockerfile'
      - 'packages/opencpu-middlelayer/.dockerignore'
  pull_request:
    paths:
      - '.github/workflows/middlelayer-tests.yml'
      - 'packages/opencpu-middlelayer/src/**'
      - 'packages/opencpu-middlelayer/__tests__/**'
      - 'packages/opencpu-middlelayer/package*.json'
      - 'packages/opencpu-middlelayer/Dockerfile'
      - 'packages/opencpu-middlelayer/.dockerignore'
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      # - name: Skip based on commit message
      #   uses: veggiemonk/skip-commit@1.0.0
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          cd packages/${SUFFIX}
          npm ci
          npm test --ci --coverage
          npm run build
        env:
          CI: 'true'
  image:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/${SUFFIX}
          docker build --label version=${GITHUB_REF##*/} --tag ${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-dev .
        env:
          CI: 'true'
