name: NGINX test and build
env:
  SUFFIX: "nginx-gateway"
  COMMIT_FILTER: "[skip-ci]"

on:
  push:
    paths:
      - '.github/workflows/nginx-tests.yml'
      - 'packages/nginx-gateway/Dockerfile'
      - 'packages/nginx-gateway/.dockerignore'
      - 'packages/nginx-gateway/default.conf'
      - 'packages/nginx-gateway/timeout.conf'
      - 'packages/nginx-gateway/package*.json'
  pull_request:
    paths:
      - '.github/workflows/nginx-tests.yml'
      - 'packages/nginx-gateway/Dockerfile'
      - 'packages/nginx-gateway/.dockerignore'
      - 'packages/nginx-gateway/default.conf'
      - 'packages/nginx-gateway/timeout.conf'
      - 'packages/nginx-gateway/package*.json'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # - name: Skip based on commit message
      #   uses: veggiemonk/skip-commit@1.0.0
      - name: Get te source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/nginx-gateway/
          docker build --label version=${GITHUB_REF##*/}  --build-arg OCPU_USER=${{secrets.OCPU_USER}} --build-arg OCPU_PW=${{secrets.OCPU_PW}} --tag "${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-dev" .
