name: OPENCPU BASE test and build
env:
  SUFFIX: "opencpu-base"
  BUILD_DATE: "2019-09-19"
  COMMIT_FILTER: "[skip-ci]"

on:
  push:
    paths:
      - '.github/workflows/ocpubase-tests.yml'
      - 'packages/opencpu-base/Dockerfile'
      - 'packages/opencpu-base/.dockerignore'
      - 'packages/opencpu-base/package*.json'
  pull_request:
    paths:
      - '.github/workflows/ocpubase-tests.yml'
      - 'packages/opencpu-base/Dockerfile'
      - 'packages/opencpu-base/.dockerignore'
      - 'packages/opencpu-base/package*.json'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # - name: Skip based on commit message
      #   uses: veggiemonk/skip-commit@1.0.0
      - name: Get te source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/opencpu-base/
          docker build --label version=${GITHUB_REF##*/} --build-arg BUILD_DATE=${BUILD_DATE} --tag "${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-dev" .
