name: Cronjob (radolan recent runner)

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: $ {{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: eu-central-1
  DWD_HTTP_HOST: ${{ secrets.DWD_HTTP_HOST }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PW: ${{ secrets.SMTP_PW }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_FROM: ${{ secrets.SMTP_FROM }}
  SMTP_ADMIN_TO: ${{ secrets.SMTP_ADMIN_TO }}

on:
  workflow_dispatch:
    {}
    # schedule:
    #   # every day at 4
    #   # https://crontab.guru/#0_4_*_*_*
    #   - cron: '0 4 * * *'
  repository_dispatch:
    types: [radolan]
jobs:
  collect_data:
    runs-on: ubuntu-latest
    name: harvesting radolan data
    defaults:
      run:
        shell: bash
        working-directory: packages/radolan-recent-to-s3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dispatcher
        run: echo "${{ github.event.client_payload.source }}"
      - name: Use Node.js from nvm
        shell: bash -l {0}
        run: nvm install
      - name: install dependencies
        run: npm ci
      - name: build 
        run: npm run build
      - name: exec radolan-recent
        run: NODE_ENV=production node ./dist/cli.js 
