name: CMS SPA test and build
on:
  push:
    paths:
      - 'sources/packages/cms-spa/src/*'
      - '.github/workflows/spa-tests.yml'
      - 'sources/packages/cms-spa/Dockerfile'
      - 'sources/packages/cms-spa/.dockerignore'
      - 'sources/packages/cms-spa/server'
      - 'sources/packages/cms-spa/package*.json'
  pull_request:
    paths:
      - 'sources/packages/cms-spa/src/*'
      - '.github/workflows/spa-tests.yml'
      - 'sources/packages/cms-spa/Dockerfile'
      - 'sources/packages/cms-spa/.dockerignore'
      - 'sources/packages/cms-spa/server'
      - 'sources/packages/cms-spa/package*.json'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          cd sources/packages/cms-spa
          npm ci
          npm test
          npm run build
        env:
          CI: "true"
  image:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: image build test
        run: |
          cd sources/packages/cms-spa
          docker build --label version=${GITHUB_REF##*/} --build-arg REACT_APP_MAPBOX_API_TOKEN=${{secrets.REACT_APP_MAPBOX_API_TOKEN}} --build-arg REACT_APP_AUTH0_DOMAIN=${{secrets.REACT_APP_AUTH0_DOMAIN}} --build-arg REACT_APP_AUTH0_CLIENTID=${{secrets.REACT_APP_AUTH0_CLIENTID}} --build-arg REACT_APP_AUTH0_AUDIENCE=${{secrets.REACT_APP_AUTH0_AUDIENCE}} --tag ${GITHUB_REPOSITORY}-cms-spa:${GITHUB_REF##*/}-dev .
        env:
          CI: "true"