name: CMS SPA test and build
env:
  SUFFIX: cms-spa
  STAGE: dev
  COMMIT_FILTER: "[skip-ci]"

on:
  push:
    paths:
      - 'packages/cms-spa/src/*'
      - '.github/workflows/spa-tests.yml'
      - 'packages/cms-spa/Dockerfile'
      - 'packages/cms-spa/.dockerignore'
      - 'packages/cms-spa/server'
      - 'packages/cms-spa/package*.json'
  pull_request:
    paths:
      - 'packages/cms-spa/src/*'
      - '.github/workflows/spa-tests.yml'
      - 'packages/cms-spa/Dockerfile'
      - 'packages/cms-spa/.dockerignore'
      - 'packages/cms-spa/server'
      - 'packages/cms-spa/package*.json'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Skip based on commit message
        uses: veggiemonk/skip-commit@1.0.0
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          cd packages/${SUFFIX}
          npm ci
          npm test --ci --coverage
          npm run build
        env:
          CI: "true"
  image:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: image build test
        run: |
          cd packages/${SUFFIX}
          docker build --label version=${GITHUB_REF##*/} --build-arg REACT_APP_MAPBOX_API_TOKEN=${{secrets.REACT_APP_MAPBOX_API_TOKEN}} --build-arg REACT_APP_AUTH0_DOMAIN=${{secrets.REACT_APP_AUTH0_DOMAIN}} --build-arg REACT_APP_AUTH0_CLIENTID=${{secrets.REACT_APP_AUTH0_CLIENTID}} --build-arg REACT_APP_AUTH0_AUDIENCE=${{secrets.REACT_APP_AUTH0_AUDIENCE}} --tag ${GITHUB_REPOSITORY}-${SUFFIX}:${GITHUB_REF##*/}-dev .
        env:
          CI: "true"