name: Node CI Test
on:
  push:
    paths:
      - 'sources/packages/cms-spa/src/*'
      - '.github/workflows/spa-test.yml'
  pull_request:
    paths:
      - 'sources/packages/cms-spa/src/*'
      - '.github/workflows/spa-test.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          cd sources/packages/cms-spa
          npm ci
          npm test
        env:
          CI: "true"