name: Jest Tests

on: [push, pull_request]
jobs:
  paths:
    - "src/*"
    - ".github/workflows/*.yml"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, test and test build
        run: |
          npm ci --quit
          npm run test:ci
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
