dist: xenial
sudo: required


language: node_js
node_js:
- '10.15.3'

before_script:
  # running code climate
  - sudo service postgresql stop
  - docker-compose up -d postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
